name: Python CI Pipeline

on:
  push:
    paths:
      - 'calculator_api/**'
      - 'todo_cli/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'calculator_api/**'
      - 'todo_cli/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies for calculator_api
      working-directory: ./calculator_api
      run: |
        pip install -r requirements.txt

    - name: Run calculator_api tests
      working-directory: ./calculator_api
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/app
        pytest || python -m unittest discover

    - name: Install dependencies for todo_cli
      working-directory: ./todo_cli
      run: |
        pip install -r requirements.txt

    - name: Run todo_cli tests
      working-directory: ./todo_cli
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/app
        pytest || python -m unittest discover