name: Multi-Project CI

on:
  push:
    paths:
      - 'TextAnalyzerCLI/**'
      - 'todo_cli/**'
      - 'ExpenseTracker/**'
      - 'WeatherCLI/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - TextAnalyzerCLI
          - todo_cli
          - ExpenseTracker
          - WeatherCLI

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest